/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team3.client;

import edu.duke.ece651.team3.client.controller.StartController;
import edu.duke.ece651.team3.client.model.Game;
import edu.duke.ece651.team3.shared.RiskGameBoard;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;

public class App extends Application {
  public static Stage stage;
  public void startView(Stage stage, String xmlPath, Game gameEntity) throws IOException {
    URL xmlResource = getClass().getResource(xmlPath);
    FXMLLoader loader = new FXMLLoader(xmlResource);
    loader.setControllerFactory((c) -> {
      return new StartController(gameEntity);
    });
    Scene scene = new Scene(loader.load(), 924, 600);

    stage.setTitle("RISC Game");
    stage.setScene(scene);
    stage.show();
  }

  @Override
  public void start(Stage primaryStage) throws IOException {
    App.stage = primaryStage;
    Thread.setDefaultUncaughtExceptionHandler(new ErrorReporter());

    Game gameEntity = new Game();

    startView(stage, "/ui/start.fxml", gameEntity);

  }

  public static void main(String[] args) {
    launch();
  }

}
