/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.team3.client.model;

import edu.duke.ece651.team3.client.ErrorReporter;
import edu.duke.ece651.team3.client.controller.StartController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;
import java.net.URL;

public class Test extends Application {
  private Stage stage;

  public void startView(Stage currStage, String xmlPath, Game gameEntity) throws IOException {
    URL xmlResource = getClass().getResource(xmlPath);
    FXMLLoader loader = new FXMLLoader(xmlResource);
    loader.setControllerFactory((c) -> {
      return new StartController(currStage, gameEntity);
    });
    Scene scene = new Scene(loader.load(), 924, 600);

    currStage.setTitle("RISC Game");
    currStage.setScene(scene);
    currStage.show();
  }

  @Override
  public void start(Stage primaryStage) throws IOException {
    this.stage = primaryStage;
    Thread.setDefaultUncaughtExceptionHandler(new ErrorReporter());

    Game gameEntity = new Game();

    startView(this.stage, "/ui/start.fxml", gameEntity);

  }

  public static void main(String[] args) {
    launch();
  }

}
